version: '3.8'

networks:
  dev:
    driver: bridge
services:
  db:
    image: 'postgres:latest'
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    user: postgres:postgres
    volumes:
      - /var/opt/pgbackups:/backups
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    networks:
      - dev
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: app/src
        - action: rebuild
          path: package.json
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1.5G
    ports:
      - '${PORT}:8080'
    environment:
      - PORT=${PORT}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - COOKIE_SECRET=${COOKIE_SECRET}
      - NODE_ENV=${NODE_ENV}
      - WEBSITE_BASE_URL=${WEBSITE_BASE_URL}
    networks:
      - dev
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
volumes:
  pgdata:
